/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2b3aa367-6a25-4fea-a2f5-0b546da10e12",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RhSyGa3cf",
    "aws_user_pools_web_client_id": "43mt1oeejahnsjp85rket9vsb5",
    "oauth": {}
};

export default awsmobile;
